name: Generate Sponsors README

on:
  workflow_dispatch:
  push: { branches: [main] }
  schedule: [cron: 0 0 * * *]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@2fd9142e765f755780202122261dc85e78459405 # v1.6.0
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"

      # ⚠️ Note: You can use any deployment step here to automatically push the README
      # changes back to your branch.
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: main
          folder: "."
