name: Generate Sponsors README

on:
  workflow_dispatch:
  push: { branches: [main] }
  schedule: [cron: 0 0 * * *]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.PAT }}
          file: "README.md"

      # ⚠️ Note: You can use any deployment step here to automatically push the README
      # changes back to your branch.
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: "."
